name: mkdocs
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocstrings[python] mkdocs-jupyter
      - run: mkdocs gh-deploy --force
        env:
          markdown_extensions:
            - pymdownx.arithmatex:
                generic: true

          extra_javascript:
            - javascripts/mathjax.js
            - https://polyfill.io/v3/polyfill.min.js?features=es6
            - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
